### ISSUE TITLE
Better support shared folder

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-dev#26]
These bugs are vagrant-related, we need to investigate if they can be fixed with vagrant 1.5 and its synced folder. In the meantime this can be used for troubleshooting.

- [ ] Can't install americano-cozy in a folder shared with Windows, the path get too long for americano-cozy/jugglingdb-adapter/request-json/request/formidable/delayed-stream/test/... 
- Bandaid : manually install jugglingdb-cozy-adapter at the top level
- [ ] Some node module failled to install due to symlinks unavailable in the VM shared folder 
- Bandait : --no-bin-links options solve most of them but not all

**Comment by jsilvestre** [comment]
Can we close this one?
