### ISSUE TITLE
[Draft] Improvements

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-dev#27]
I suggest we list here the improvements we want to see in order to test feasibility and just get them done if possible.

- better support for Windows / share folder (see #26)
- better development workflow : 
```bash
cozy-dev new myapp --coffee
cd myapp/
cozy-dev start myapp # start a nodemon in /vagrant/myapp, create authorization and stuff
# log is displayed here OR it's available somewhere else (e.g. cozy-dev log == cozy-monitor log but for /vagrant/app/log/development.log)
# brunch must still be started in another terminal
```

- rename "dev:*" commands to be easier to understand/use
- rename "light-update" command to "update"
- doesn't depend on Github anymore, can use any Git provider (see #17)
- proxy support (well that's a more general issue related to the platform itself too) (see #20)

**Comment by jsilvestre** [comment]
Actually, replacing `deploy` command from "deploy to a production Cozy" to "start within the vagrant VM"

**Comment by m4dz** [comment]
:+1:

**Comment by jsilvestre** [comment]
Closing this since it has been mostly taken into account in the last changes
