### ISSUE TITLE
Deploy command looks broken

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-dev#46]
A user reports that running the deploy command at the end of the tutorial leads to an error. It's related to the configuration file. I don't have the exact error message. This bug requires more investigation.

**Comment by jsilvestre** [comment]
I suggest we replace this command with the following behaviour: "run the app within the VM" which is far less random about if the dev has an actual Cozy running somewhere, requires no configuration, is something that will help testing an app in a real environment.

**Comment by bnjbvr** [comment]
That seems fixed by the latest deploy improvements. Should this issue be closed?

**Comment by frankrousseau** [comment]
Yes
