### ISSUE TITLE
error when "vagrant up"

### ISSUE THREAD

**Issue by cylwin** [cozy/cozy-dev#67]
vagrant up end with :
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
/sbin/ifup eth1
Stdout from the command:

Stderr from the command:
stdin: is not a tty
/etc/network/interfaces:51: interface eth2 declared allow-auto twice
/sbin/ifup: couldn't read interfaces file "/etc/network/interfaces"
```
When I run cozy-dev vm:start, I have no error message, but I think that the process stop at this moment also because the shared folder is not set.

In order to fix this I modified my VagrantFile commenting : 
`  #config.vm.network :private_network, ip: "192.168.50.4"`
and it works :-)

**Comment by poupotte** [comment]
Thanks @cylwin . This issue seems come from a vagrant issue : https://github.com/mitchellh/vagrant/issues/5279.

**Comment by cylwin** [comment]
Yes, I saw this vagrant issue, and I fixed the problem thanks to it.
But is this line very important for the dev env : `config.vm.network :private_network, ip: "192.168.50.4"` ?

Vagrant (v1.7.2) is the version required in http://cozy.io/en/hack/getting-started/setup-environment.html

**Comment by jsilvestre** [comment]
It's not important at all unless your are doing specific stuff.
