### ISSUE TITLE
Add mailcatcher to VM dev

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-dev#75]
Hi,

as talked with @poupotte, it could be useful to have a tool to test the mails sent by the cozy platform during development. I'm using [mailcatcher](http://mailcatcher.me/) to do this in many projects. It's a ruby app that simulates a sendmail service on the host and catch all sent mails to display them in a dead-simple webmail interface.

## Steps to install:
1. install ruby > 1.9.1 and sqlite-dev libs:
```shell
apt-get install ruby1.9.3 libsqlite3-dev
```
2. install mailcatcher using gem: 
```shell
gem1.9.3 install mailcatcher --no-ri --no-rdoc
```

## Steps to run:
We should start the mailcatchr app with supervisor so it will always be accessible

```ini
[program:mailcatcher]
autorestart=true
command=/usr/local/bin/mailcatcher
    --http-ip=0.0.0.0
    --smtp-port=25
    --no-quit
    --foreground
redirect_stderr=true
user=root
```

We also need a new forwarding rule to access the mailcatcher web interface in the Vagrantfile:
```
  config.vm.network :forwarded_port, guest: 1080, host: 1080 # Mailcatcher
```

Thanks, it'll help us a lot for debugging mailings :smile:!

**Comment by frankrousseau** [comment]
Looks super cool. +1

**Comment by poupotte** [comment]
Mailcatcher has been added in 0.11.0
